// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This will generate sidebar from docs/ folder structure
    },
  ],
  personalizedBeginnerSidebar: [
    {
      type: 'autogenerated',
      dirName: 'personalized-beginner',
    },
  ],
  personalizedIntermediateSidebar: [
    {
      type: 'autogenerated',
      dirName: 'personalized-intermediate',
    },
  ],
  personalizedAdvancedSidebar: [
    {
      type: 'autogenerated',
      dirName: 'personalized-advanced',
    },
  ],
  urduSidebar: [
    {
      type: 'autogenerated',
      dirName: 'urdu',
    },
  ],
};

module.exports = sidebars;