// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  urduSidebar: [
    {
      type: 'autogenerated',
      dirName: '.', // This will generate sidebar from the current plugin's folder structure
    },
  ],
};

module.exports = sidebars;