/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Physical AI & Humanoid Robotics",
  "tagline": "A comprehensive textbook on Physical AI and Humanoid Robotics",
  "url": "https://your-domain.io",
  "baseUrl": "/",
  "onBrokenLinks": "throw",
  "onBrokenMarkdownLinks": "warn",
  "favicon": "img/favicon.ico",
  "organizationName": "physical-ai-hackathon",
  "projectName": "spec-kit-plus",
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "D:\\physical-ai-hackathon\\spec-kit-plus\\sidebars.js",
          "editUrl": "https://github.com/physical-ai-hackathon/spec-kit-plus/edit/main/",
          "path": "docs",
          "routeBasePath": "docs"
        },
        "blog": false,
        "theme": {
          "customCss": "D:\\physical-ai-hackathon\\spec-kit-plus\\src\\css\\custom.css"
        }
      }
    ]
  ],
  "plugins": [
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "personalized-beginner",
        "path": "docs-personalized/beginner",
        "routeBasePath": "docs/personalized-beginner",
        "sidebarPath": "D:\\physical-ai-hackathon\\spec-kit-plus\\sidebars-beginner.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "personalized-intermediate",
        "path": "docs-personalized/intermediate",
        "routeBasePath": "docs/personalized-intermediate",
        "sidebarPath": "D:\\physical-ai-hackathon\\spec-kit-plus\\sidebars-intermediate.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "personalized-advanced",
        "path": "docs-personalized/advanced",
        "routeBasePath": "docs/personalized-advanced",
        "sidebarPath": "D:\\physical-ai-hackathon\\spec-kit-plus\\sidebars-advanced.js"
      }
    ],
    [
      "@docusaurus/plugin-content-docs",
      {
        "id": "urdu",
        "path": "docs-urdu",
        "routeBasePath": "docs/urdu",
        "sidebarPath": "D:\\physical-ai-hackathon\\spec-kit-plus\\sidebars-urdu.js"
      }
    ]
  ],
  "themeConfig": {
    "image": "img/docusaurus-social-card.jpg",
    "navbar": {
      "title": "Physical AI & Humanoid Robotics",
      "logo": {
        "alt": "Physical AI Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "type": "docSidebar",
          "sidebarId": "tutorialSidebar",
          "position": "left",
          "label": "Textbook"
        },
        {
          "type": "dropdown",
          "label": "Personalized Content",
          "position": "left",
          "items": [
            {
              "label": "Beginner Level",
              "to": "/docs/personalized-beginner/intro-beginner"
            },
            {
              "label": "Intermediate Level",
              "to": "/docs/personalized-intermediate/intro-intermediate"
            },
            {
              "label": "Advanced Level",
              "to": "/docs/personalized-advanced/intro-advanced"
            }
          ]
        },
        {
          "type": "dropdown",
          "label": "Urdu Content",
          "position": "left",
          "items": [
            {
              "label": "اردو تعارف",
              "to": "/docs/urdu/intro"
            },
            {
              "label": "Urdu Embodied Intelligence",
              "to": "/docs/urdu/physical-ai/embodied-intelligence"
            },
            {
              "label": "Urdu Sensors",
              "to": "/docs/urdu/physical-ai/sensors"
            }
          ]
        },
        {
          "href": "https://github.com/physical-ai-hackathon/spec-kit-plus",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Docs",
          "items": [
            {
              "label": "Textbook",
              "to": "/docs/intro"
            }
          ]
        },
        {
          "title": "Community",
          "items": [
            {
              "label": "Stack Overflow",
              "href": "https://stackoverflow.com/questions/tagged/docusaurus"
            },
            {
              "label": "Discord",
              "href": "https://discordapp.com/invite/docusaurus"
            },
            {
              "label": "Twitter",
              "href": "https://twitter.com/docusaurus"
            }
          ]
        },
        {
          "title": "More",
          "items": [
            {
              "label": "GitHub",
              "href": "https://github.com/facebook/docusaurus"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2025 Physical AI & Humanoid Robotics Project. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "metadata": [],
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "baseUrlIssueBanner": true,
  "i18n": {
    "defaultLocale": "en",
    "path": "i18n",
    "locales": [
      "en"
    ],
    "localeConfigs": {}
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    }
  }
};
